updated awscli run

diff --git a/.github/workflows/deploy-docs.yaml b/.github/workflows/deploy-docs.yaml
--- a/.github/workflows/deploy-docs.yaml
+++ b/.github/workflows/deploy-docs.yaml
@@ -24,8 +24,14 @@ jobs:
 
     - name: Install AWS CLI
       run: |
-        sudo apt-get update
-        sudo apt-get install -y awscli
+        if ! command -v aws &> /dev/null; then
+          echo "AWS CLI not found. Installing..."
+          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+          unzip awscliv2.zip
+          sudo ./aws/install
+        else
+          echo "AWS CLI already installed."
+        fi
 
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v2
